spring.datasource:
  url: jdbc:h2:./camunda-db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
#shareable h2 database: jdbc:h2:./camunda-db;DB_CLOSE_DELAY=-1;MVCC=TRUE;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE
  username: sa
  password: sa
#spring:
#    datasource:
#        url: jdbc:mysql://localhost:3306/profiles_service?createDatabaseIfNotExist=true
#        username: root
#        password: rootPassword
#        driver-class-name: com.mysql.cj.jdbc.Driver
#        initialization-mode: always
#spring.h2.console.enabled: true
#camunda.bpm:
#  admin-user:
#    id: demo
#    password: demo
#    firstName: Demo
#  filter:
#    create: All tasks
#server.port: 9090

#eureka:
#  client:
#    register-with-eureka: true
#    service-url:
#      default-zone: http://localhost:8761/eureka
##eureka.client.service-url.defaultZone= http://localhost:8761/eureka
#spring:
#    data:
#        mongodb:
#            database: profiles_service
#            #authentication-database: admin
#            #username: root
#            #password: root
#            port: 27017
#            host: localhost
#            uri: mongodb://localhost:27017
#    main:
#        allow-bean-definition-overriding: true
#
#spring.datasource:
#    #    url: jdbc:h2:./camunda-db;DB_CLOSE_DELAY=-1;MVCC=TRUE;DB_CLOSE_ON_EXIT=FALSE
#    #    #shareable h2 database: jdbc:h2:./camunda-db;DB_CLOSE_DELAY=-1;MVCC=TRUE;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE
#    #    username: sa
#    #    password: sa
#    #spring.h2.console.enabled: true
#    #    url: jdbc:h2:./camunda-db;DB_CLOSE_DELAY=-1;MVCC=TRUE;DB_CLOSE_ON_EXIT=FALSE
#    #    #shareable h2 database: jdbc:h2:./camunda-db;DB_CLOSE_DELAY=-1;MVCC=TRUE;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE
#    #    username: sa
#    #    password: sa
#
#    #  datasource:
#        url: jdbc:postgresql://10.170.4.67:5432/camunda
#        username: postgres
#        password: rootPassword
#        driver-class-name: org.postgresql.Driver
#        initialization-mode: always
#        jpa:
#            hibernate:
#                naming:
#                    physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#                ddl-auto: create-drop
#            properties:
#                hibernate:
#                    show_sql: true
#                    format_sql: true
    #spring.h2.console.enabled: true
#    url: jdbc:mysql://10.170.3.46:3306/camunda?createDatabaseIfNotExist=true
#    username: root
#    password: rootPassword
#    driver-class-name: com.mysql.jdbc.Driver
#    initialization-mode: always
#    jpa:
#        hibernate:
#            naming:
#                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#            ddl-auto: create-drop
#        properties:
#            hibernate:
#                show_sql: true
#                format_sql: true
#spring.h2.console.enabled: true

camunda.bpm:
    admin-user:
        id: demo
        password: Demo12345*
        firstName: Demo
    filter:
        create: All tasks
    authorization: true
server:
 port: 9091
eureka:
    client:
        register-with-eureka: true
        service-url:
            default-zone: http://10.170.4.67:8761/eureka

#eureka.client.service-url.defaultZone= http://localhost:8761/eureka
spring:
    mail:
      host: smtp.gmail.com
      port: 587
      username: whatiemusah@gmail.com
      password: bhhewfzduaefdphq
      properties:
        mail:
          smtp:
            auth: true
            starttls:
              enable: true
    data:
        mongodb:
            database: profiles_service
            #authentication-database: admin
            #username: root
            #password: root
            port: 27017
            host: 10.170.4.127
            uri: mongodb://10.170.4.127:27017
    main:
        allow-bean-definition-overriding: true
    cloud:
        consul:
            host: 10.170.4.67
            port: 8500
            discovery:
                prefer-ip-address: true
                ip-address: 10.170.4.67
                health-check-path: /health
    #eureka.client.se
configurations:
    sanctionsScreening:
        http://10.170.3.40:9781/kyc-screening-service/screen
    zssSMSUrl:
        https://secure.zss.co.zw/vportal/cnm/vsms/plain
    userName:
        sbaera
    password:
        sharon12*
    gatewayUrl:
        http://10.170.4.67:8080/handler/api
    sanctionsScreeningUrl:
        http://fbconline:9781/kyc-screening-service/screen
    registrarApi:
        http://10.170.4.67:8080/handler/api/registrar-service/person
    bpmUrl:
        http://10.170.4.67:9090
    regGeneralUrl:
        http://10.170.4.67:8080/handler/api/registrar-service/person/
    postilionUrl:
        http://localhost:9090/v1/accountcreation
    fcbUrl:
        https://www.fcbureau.co.zw/api/newIndividual
feign:
    client:
        config:
            default:
                connect-timeout:  800000000
                read-timeout: 800000000
camunda:
    bpm:
        generic-properties:
            properties:
                enable-password-policy: true
        database:
            schema-update: true
        authorization:
            enabled: true
            tenant-check-enabled: false
        job-execution:
            enabled: true
        history-level: FULL

#camunda.bpm.authorization.tenant-check-enabled
#camunda:
#  bpm:
#    database:
#      schema-update: true
#    job-execution:
#      enabled: false
#    authorization:
#      enabled: true
#      tenant-check-enabled: true
#    process-engine-name: testEngine
#    history-level: none

management:
    endpoint:
        health:
            show-details: always
        beans:
            enabled: true
        consul:
            enabled: true
    endpoints:
        web:
            exposure:
                include: '*'
            base-path: /
        enabled-by-default: true
    health:
        defaults:
            enabled: true

